{% set name = "zlib-ng" %}
{% set version = "0.2.0" %}

package:
  name: python-zlib-ng    # To avoid confusion with zlib-ng proper
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b23707cb7e5bf27afd8422d290f68e82185af69741bde60914f18d16fb66e9b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - PYTHON_ZLIB_NG_LINK_DYNAMIC=true  # Forces a dynamic link against zlib-ng in conda-forge
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - zlib-ng >=2.0.6
  run:
    - python
    - zlib-ng >=2.0.6
test:
  imports:
    - zlib_ng
  commands:
    - python -c "from zlib_ng import gzip_ng"
    - python -c "from zlib_ng import zlib_ng; zlib_ng.adler32(b'test')"
about:
  home: https://github.com/pycompression/python-zlib-ng
  license: PSF-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Drop-in replacement for zlib and gzip modules using zlib-ng
  doc_url: https://python-zlib-ng.readthedocs.io
  dev_url: https://github.com/pycompression/python-zlib-ng

extra:
  recipe-maintainers:
    - rhpvorderman
